version: '2'
services:
  db:
    container_name: rosebud-api-db-development
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=blog
    ports:
      - "3306:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf